create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tech_stack text not null,
  image_url text,
  github_url text,
  live_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('language', 'tool', 'concept')),
  level int not null check (level between 1 and 5)
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  icon text not null
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.services enable row level security;
alter table public.messages enable row level security;

drop policy if exists "public read projects" on public.projects;
create policy "public read projects"
on public.projects
for select
to anon, authenticated
using (true);

drop policy if exists "public read skills" on public.skills;
create policy "public read skills"
on public.skills
for select
to anon, authenticated
using (true);

drop policy if exists "public read services" on public.services;
create policy "public read services"
on public.services
for select
to anon, authenticated
using (true);

drop policy if exists "public insert messages" on public.messages;
create policy "public insert messages"
on public.messages
for insert
to anon, authenticated
with check (true);

drop policy if exists "auth read messages" on public.messages;
create policy "auth read messages"
on public.messages
for select
to authenticated
using (true);

drop policy if exists "auth manage projects" on public.projects;
create policy "auth manage projects"
on public.projects
for all
to authenticated
using (true)
with check (true);
